CREATE TABLE l1_message (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    msg_id INTEGER NOT NULL,
    msg_data TEXT NOT NULL,
    l2_ticket_id VARCHAR(66) NOT NULL,
    status VARCHAR(36) NOT NULL, -- SENT, RETRYABLE, DONE
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
